import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export struct AdderGlobalData {
    x: int,
    y: int,
    sum: int,
}

export global AdderGlobal {
    in-out property <[AdderGlobalData]> data: [{}];
}

export component AdderGlobalComponent inherits Rectangle {
    in-out property <int> global-data-length: AdderGlobal.data.length;
    in-out property <int> global-data-index: 0;
    in-out property <int> global-x: AdderGlobal.data[global-data-index].x;
    changed global-x => { AdderGlobal.data[global-data-index].x = self.global-x; }
    in-out property <int> global-y: AdderGlobal.data[global-data-index].y;
    changed global-y => { AdderGlobal.data[global-data-index].y = self.global-y; }
    out property <int> global-sum: AdderGlobal.data[global-data-index].sum;
}

export component Adder inherits AdderGlobalComponent {
    VerticalBox {
        Text {
            text: "X: " + root.global-x;
        }

        HorizontalBox {
            Button {
                text: "+";
                clicked => {
                    root.global-x += 1;
                }
            }

            Button {
                text: "-";
                clicked => {
                    root.global-x -= 1;
                }
            }
        }

        Text {
            text: "Y: " + root.global-y;
        }

        HorizontalBox {
            Button {
                text: "+";
                clicked => {
                    root.global-y += 1;
                }
            }

            Button {
                text: "-";
                clicked => {
                    root.global-y -= 1;
                }
            }
        }

        Text {
            text: "Sum: " + root.global-sum;
            font-size: 24px;
            horizontal-alignment: center;
        }
    }
}
