import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export struct AddersGlobalData {
    values: [int],
    sum: int,
}

export global AddersGlobal {
    in-out property <[AddersGlobalData]> data: [{}];
}

export component AddersGlobalComponent inherits Rectangle {
    in-out property <int> global-data-length: AddersGlobal.data.length;
    in-out property <int> global-data-index: 0;
    in-out property <[int]> global-values: AddersGlobal.data[global-data-index].values;
    changed global-values => { AddersGlobal.data[global-data-index].values = self.global-values; }
    out property <int> global-sum: AddersGlobal.data[global-data-index].sum;
}

export component Adders inherits AddersGlobalComponent {
    VerticalBox {
        Text {
            text: "AdderVec[" + root.global-data-index + "]";
        }

        for value[i] in root.global-values: VerticalBox {
            Text {
                text: "Value[" + i + "]: " + value;
            }

            HorizontalBox {
                Button {
                    text: "+";
                    clicked => {
                        root.global-values[i] += 1;
                    }
                }

                Button {
                    text: "-";
                    clicked => {
                        root.global-values[i] -= 1;
                    }
                }
            }
        }

        Text {
            text: "Sum: " + root.global-sum;
            font-size: 24px;
            horizontal-alignment: center;
        }
    }
}
