import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { AddersGlobalComponent } from "../global/adders.slint";

export component Adders inherits AddersGlobalComponent {
    VerticalBox {
        Text {
            text: "AdderVec[" + root.global-index + "]";
        }

        for value[i] in root.global-values: VerticalBox {
            Text {
                text: "Value[" + i + "]: " + value;
            }

            HorizontalBox {
                Button {
                    text: "+";
                    clicked => {
                        root.global-values[i] += 1;
                    }
                }

                Button {
                    text: "-";
                    clicked => {
                        root.global-values[i] -= 1;
                    }
                }
            }
        }

        Text {
            text: "Sum: " + root.global-sum;
            font-size: 24px;
            horizontal-alignment: center;
        }
    }
}
