import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export global AdderData {
    in-out property <[int]> x;
    in-out property <[int]> y;
    in property <int> sum;
}

export component Adder inherits Rectangle {
    VerticalBox {
        Text {
            text: "X: " + AdderData.x[0];
        }

        HorizontalBox {
            Button {
                text: "+";
                clicked => {
                    AdderData.x[0] += 1;
                }
            }

            Button {
                text: "-";
                clicked => {
                    AdderData.x[0] -= 1;
                }
            }
        }

        Text {
            text: "Y: " + AdderData.y[0];
        }

        HorizontalBox {
            Button {
                text: "+";
                clicked => {
                    AdderData.y[0] += 1;
                }
            }

            Button {
                text: "-";
                clicked => {
                    AdderData.y[0] -= 1;
                }
            }
        }

        Text {
            text: "Sum: " + AdderData.sum;
            font-size: 24px;
            horizontal-alignment: center;
        }
    }
}
