import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export struct AdderArrayData {
    values: [int],
    sum: int,
}

export global AdderArrayDataGlobal {
    in-out property <[AdderArrayData]> data;
}

component AdderArrayDataComponent inherits Rectangle {
    in-out property <int> global-index: 0;
    in-out property <[int]> global-values: AdderArrayDataGlobal.data[global-index].values;
    changed global-values => { AdderArrayDataGlobal.data[global-index].values = self.global-values; }
    out property <int> global-sum: AdderArrayDataGlobal.data[global-index].sum;
}

export component AdderArray inherits AdderArrayDataComponent {
    VerticalBox {
        Text {
            text: "AdderArray[" + root.global-index + "]";
        }

        for value[i] in root.global-values: VerticalBox {
            Text {
                text: "Value[" + i + "]: " + value;
            }

            HorizontalBox {
                Button {
                    text: "+";
                    clicked => {
                        root.global-values[i] += 1;
                    }
                }

                Button {
                    text: "-";
                    clicked => {
                        root.global-values[i] -= 1;
                    }
                }
            }
        }

        Text {
            text: "Sum: " + root.global-sum;
            font-size: 24px;
            horizontal-alignment: center;
        }
    }
}
