import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export struct AdderVecData {
    values: [int],
    sum: int,
}

export global AdderVecDataGlobal {
    in-out property <[AdderVecData]> data: [{}];
}

component AdderVecDataComponent inherits Rectangle {
    in-out property <int> global-index: 0;
    in-out property <[int]> global-values: AdderVecDataGlobal.data[global-index].values;
    changed global-values => {
        AdderVecDataGlobal.data[global-index].values = self.global-values;
    }
    out property <int> global-sum: AdderVecDataGlobal.data[global-index].sum;
}

export component AdderVec inherits AdderVecDataComponent {
    VerticalBox {
        Text {
            text: "AdderVec[" + root.global-index + "]";
        }

        for value[i] in root.global-values: VerticalBox {
            Text {
                text: "Value[" + i + "]: " + value;
            }

            HorizontalBox {
                Button {
                    text: "+";
                    clicked => {
                        root.global-values[i] += 1;
                    }
                }

                Button {
                    text: "-";
                    clicked => {
                        root.global-values[i] -= 1;
                    }
                }
            }
        }

        Text {
            text: "Sum: " + root.global-sum;
            font-size: 24px;
            horizontal-alignment: center;
        }
    }
}
