import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export struct AdderArrayData {
    x: [int],
    y: [int],
    sum: [int],
}

export global AdderArrayDataGlobal {
    in-out property <[AdderArrayData]> data;
}

export component AdderArray inherits Rectangle {
    in property <int> index;

    VerticalBox {
        Text {
            text: "AdderArray[" + index + "]";
        }

        Text {
            text: "X: " + AdderArrayDataGlobal.data[0].x[index];
        }

        HorizontalBox {
            Button {
                text: "+";
                clicked => {
                    AdderArrayDataGlobal.data[0].x[index] += 1;
                }
            }

            Button {
                text: "-";
                clicked => {
                    AdderArrayDataGlobal.data[0].x[index] -= 1;
                }
            }
        }

        Text {
            text: "Y: " + AdderArrayDataGlobal.data[0].y[index];
        }

        HorizontalBox {
            Button {
                text: "+";
                clicked => {
                    AdderArrayDataGlobal.data[0].y[index] += 1;
                }
            }

            Button {
                text: "-";
                clicked => {
                    AdderArrayDataGlobal.data[0].y[index] -= 1;
                }
            }
        }

        Text {
            text: "Sum: " + AdderArrayDataGlobal.data[0].sum[index];
            font-size: 24px;
            horizontal-alignment: center;
        }
    }
}
