import { LineEdit, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { RepeaterGlobalComponent } from "../global/repeater.slint";

export component Repeater inherits RepeaterGlobalComponent {
    VerticalBox {
        Text {
            text: "Repeater";
            font-size: 20px;
            horizontal-alignment: center;
        }

        HorizontalBox {
            Text {
                text: "Input:";
                vertical-alignment: center;
            }

            LineEdit {
                placeholder-text: "Enter text (max 20 chars)";
                text <=> root.global-text;
            }
        }

        Text {
            text: "Repeated: " + root.global-repeated;
            font-size: 16px;
        }
    }
}
