import { LineEdit, VerticalBox, HorizontalBox } from "std-widgets.slint";

export struct RepeaterGlobalData {
    text: string,
    repeated: string,
}

export global RepeaterGlobal {
    in-out property <[RepeaterGlobalData]> data: [{}];
}

export component RepeaterGlobalComponent inherits Rectangle {
    in-out property <int> global-data-length: RepeaterGlobal.data.length;
    in-out property <int> global-data-index: 0;
    in-out property <string> global-text: RepeaterGlobal.data[global-data-index].text;
    changed global-text => { RepeaterGlobal.data[global-data-index].text = self.global-text; }
    out property <string> global-repeated: RepeaterGlobal.data[global-data-index].repeated;
}

export component Repeater inherits RepeaterGlobalComponent {
    VerticalBox {
        Text {
            text: "Repeater";
            font-size: 20px;
            horizontal-alignment: center;
        }

        HorizontalBox {
            Text {
                text: "Input:";
                vertical-alignment: center;
            }

            LineEdit {
                placeholder-text: "Enter text (max 20 chars)";
                text <=> root.global-text;
            }
        }

        Text {
            text: "Repeated: " + root.global-repeated;
            font-size: 16px;
        }
    }
}
