import { ScreenGlobal, Screen } from "screen/screen.slint";
import { AdderGlobal } from "components/adder.slint";
import {
    AdderVecGlobal,
} from "components/adder_array.slint";
import { RepeaterGlobal } from "components/repeater.slint";

export { ScreenGlobal, AdderGlobal, AdderVecGlobal, RepeaterGlobal }

export component MainWindow inherits Window {
    title: "Main";
    min-width: 300px;
    min-height: 1300px;

    Screen { }
}
