import { ScreenData, ScreenDataGlobal, Screen } from "screen/screen.slint";
import { AdderData, AdderDataGlobal } from "components/adder.slint";
import {
    AdderArrayData,
    AdderArrayDataGlobal,
} from "components/adder_array.slint";

export { ScreenData, ScreenDataGlobal, AdderData, AdderDataGlobal, AdderArrayData, AdderArrayDataGlobal }

export component MainWindow inherits Window {
    title: "Main";
    min-width: 300px;
    min-height: 1000px;

    Screen { }
}
