import { ScreenData, ScreenDataGlobal, Screen } from "screen/screen.slint";
import { AdderData, AdderDataGlobal } from "components/adder.slint";
import {
    AdderVecData,
    AdderVecDataGlobal,
} from "components/adder_array.slint";
import { RepeaterData, RepeaterDataGlobal } from "components/repeater.slint";

export { ScreenData, ScreenDataGlobal, AdderData, AdderDataGlobal, AdderVecData, AdderVecDataGlobal, RepeaterData, RepeaterDataGlobal }

export component MainWindow inherits Window {
    title: "Main";
    min-width: 300px;
    min-height: 1300px;

    Screen { }
}
