import { StartScreen } from "start.slint";
import { PayScreen } from "pay.slint";

export enum ScreenVariant {
    Start,
    Pay
}

export struct ScreenData {
    current-screen: ScreenVariant,
}

export global ScreenDataGlobal {
    in-out property <[ScreenData]> data;
    callback confirm-start();
    callback cancel-pay();
}

export component Screen inherits Rectangle {
    if ScreenDataGlobal.data[0].current-screen == ScreenVariant.Start: StartScreen {
        on-confirm => {
            ScreenDataGlobal.confirm-start()
        }
    }
    if ScreenDataGlobal.data[0].current-screen == ScreenVariant.Pay: PayScreen {
        on-cancel => {
            ScreenDataGlobal.cancel-pay()
        }
    }
}
