import { StartScreen } from "start.slint";
import { PayScreen } from "pay.slint";
import { ScreenGlobalComponent, ScreenVariant } from "../global/screen.slint";

export component Screen inherits ScreenGlobalComponent {
    if root.global-current-screen == ScreenVariant.Start: StartScreen {
        on-confirm => {
            root.global-confirm-start();
        }
    }
    if root.global-current-screen == ScreenVariant.Pay: PayScreen {
        on-cancel => {
            root.global-cancel-pay();
        }
    }
}
