import { StartScreen } from "start.slint";
import { PayScreen } from "pay.slint";

export enum ScreenVariant {
    Start,
    Pay
}

export global ScreenData {
    in property <ScreenVariant> current-screen;
    callback confirm-start();
    callback cancel-pay();
}

component ScreenDataSystem {

}

export component Screen inherits Rectangle {
    ScreenDataSystem {}

    if ScreenData.current-screen == ScreenVariant.Start: StartScreen {
        on-confirm => { ScreenData.confirm-start() }
    }
    
    if ScreenData.current-screen == ScreenVariant.Pay: PayScreen {
        on-cancel => { ScreenData.cancel-pay() }    
    }
}