import { Button, VerticalBox } from "std-widgets.slint";
import { Adder } from "../components/adder.slint";
import { Adders } from "../components/adders.slint";
import { Repeater } from "../components/repeater.slint";
import { AddersGlobal } from "../components/adders.slint";

export component StartScreen inherits Rectangle {
    callback on-confirm();

    VerticalBox {
        Text {
            text: "Start Screen";
            font-size: 24px;
            horizontal-alignment: center;
        }

        Repeater { }

        Adder { }

        for item[i] in AddersGlobal.data: Adders {
            global-data-index: i;
        }

        Button {
            text: "Confirm";
            clicked => {
                root.on-confirm();
            }
        }
    }
}
