import { Button, VerticalBox } from "std-widgets.slint";
import { Adder } from "../components/adder.slint";
import { AdderArray } from "../components/adder_array.slint";

export component StartScreen inherits Rectangle {
    callback on-confirm();

    VerticalBox {
        Text {
            text: "Start Screen";
            font-size: 24px;
            horizontal-alignment: center;
        }

        Adder { }

        AdderArray { index: 0; }

        AdderArray { index: 1; }

        Button {
            text: "Confirm";
            clicked => {
                root.on-confirm();
            }
        }
    }
}
